version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirement.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package...." 
      - cd lib
      - zip -r9 ../deployment_package.zip
      - cd ..
      - zip -g deployment_package.zip lamda_function.py
  post_build:
    commands:
      - echo "Uploading to s3...."
      - aws s3 cp deployment_package.zip s3://lambda-build-zip-new/
      - echo "Updating Lambda function via s3.."
      - aws lambda update-function-code --function-name cicd-code-lambda --s3-bucket lambda-build-zip-new --s3-key deployment_package.zip
      - echo "Deployment complete" 